routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/home', function () {
    return view('welcome');
});

Auth::routes();

//Route::get('/categories/order','CategoryController@order')->middleware('admin')->name('categories.order');

Route::resource('categories', 'CategoryController')->middleware('admin');


Route::resource('collections', 'CollectionController')->middleware('admin');
Route::resource('hobbies', 'HobbyController')->middleware('admin');
Route::post('hobbies/create/get_cate_id_by_collection_id','CategoryController@get_cate_by_collection_id');

Route::resource('activities', 'ActivityController')->middleware('admin');
Route::resource('items', 'ItemController')->middleware('admin');

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{

    protected $fillable = [
        'name','description','point','money','image_url'
    ];
}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Item;
use App\ItemUser;
use Illuminate\Http\Request;

class ItemController extends Controller
{
    public function index()
    {
        $items=Item::all();
        return view('item.index',compact('items'));
    }

    public function create()
    {
        return view('item.create');
    }

    public function buy(Request $request){
        $user=Auth::user();
        $item=Item::find($request->item_id);
        $user->point=$user->point-$item->point;
        $user->money=$user->money-$item->money;
        $user->save();
        //$item_user=ItemUser::where('user_id',$user->id)->where('item_id',$item->id)->get();

    }

    public function all(){

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $item=new Item();
        $item->name=$request->name;
        $item->description=$request->description;
        $item->point=$request->point;
        $item->money=$request->money;
        if($request->has('image_url') && $file = $request->file('image_url')){
            if ($file->isValid()) {
                $img_path = $file->store('items_image');
                $item->image_url=$img_path;
            }
        }
        $item->save();
        return redirect(action('ItemController@index'))->with('success','更新成功');


        /* $collection = new Collection();
         $collection->name = $request->get('name');
         $collection->save();
         return redirect('collections')->with('success','已添加类别');*/
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item=Item::find($id);
        return view('item.edit',compact('item','id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $item=Item::find($id);
        $item->name=$request->name;
        $item->description=$request->description;
        $item->point=$request->point;
        $item->money=$request->money;
        if($request->has('image_url') && $file = $request->file('image_url')){
            if ($file->isValid()) {
                $img_path = $file->store('items_image');
                $item->image_url=$img_path;
            }
        }
        $item->save();
        return redirect(action('ItemController@index'))->with('success','更新成功');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

    }
}

resources/views/item/create.blade.php
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <meta name="csrf-token" content="{{ csrf_token() }}">
</head>
@extends('layouts.app')

@section('content')

    @include('layouts.feedback')
    @include('item.item_tab')
    <div class="container-fluid mt-2 mb-5">

        <div class="card">

                <div class="card-footer">
                    <form method="post" action="{{ action('ItemController@store') }}" enctype="multipart/form-data">
                    @csrf

                            <div class="mb-3">
                                <div class="mb-2">
                                    <span class="text-left"><b>图片上传</b></span>
                                </div>
                                <div class="bg-white row pl-3 pr-3 pt-2 pb-2">
                                    <div class="w-100">
                                        <input type="file" class="form-control {{ $errors->has('image_url') ? ' is-invalid' : '' }} border-0 w-100" name="image_url" id="image_url"
                                               required>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">名称</label>
                                <div class="col-md-6">
                                    <input type="text" class="border-0 w-100 form-control {{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" id="name"
                                           required >
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="description" class="col-md-4 col-form-label text-md-right">描述</label>
                                <div class="col-md-6">
                                    <input type="text" class="border-0 w-100 form-control {{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" id="description"
                                           required >
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="point" class="col-md-4 col-form-label text-md-right">积分</label>
                                <div class="col-md-6">
                                    <input type="number" class="border-0 w-100 form-control {{ $errors->has('points') ? ' is-invalid' : '' }}" name="point" id="point"
                                           required >
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="money" class="col-md-4 col-form-label text-md-right">银两</label>
                                <div class="col-md-6">
                                    <input type="number" class="border-0 w-100 form-control {{ $errors->has('money') ? ' is-invalid' : '' }}" name="money" id="money"
                                           required >
                                </div>
                            </div>



                            <button type="submit" class="btn btn-info btn-block">上传</button>
                    </form>
                </div>
            </div>

    </div>

@endsection

resources/views/item/edit.blade.php
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
    <meta name="csrf-token" content="{{ csrf_token() }}">
</head>
@extends('layouts.app')

@section('content')

    @include('layouts.feedback')
    @include('item.item_tab')
    <div class="container-fluid mt-2 mb-5">
        <div class="card">

            <div class="card-footer">
                <form method="post" action="{{ action('ItemController@update',$id) }}" enctype="multipart/form-data">
                    @csrf

                    @include('layouts.feedback')
                    <input name="_method" type="hidden" value="PATCH">
                    <div class="mb-3">
                        <div class="mb-2">
                            <span class="text-left"><b>图片上传</b></span>
                        </div>
                        <div class="bg-white row pl-3 pr-3 pt-2 pb-2">
                            <div class="w-100">
                                <input type="file" class="form-control {{ $errors->has('image_url') ? ' is-invalid' : '' }} border-0 w-100" name="image_url" id="image_url">
                            </div>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="name" class="col-md-4 col-form-label text-md-right">名称</label>
                        <div class="col-md-6">
                            <input type="text" class="border-0 w-100 form-control {{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" id="name"
                                   required value={{$item->name}} >
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="description" class="col-md-4 col-form-label text-md-right">描述</label>
                        <div class="col-md-6">
                            <input type="text" class="border-0 w-100 form-control {{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" id="description"
                                   required value={{$item->description}}>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="point" class="col-md-4 col-form-label text-md-right">积分</label>
                        <div class="col-md-6">
                            <input type="number" class="border-0 w-100 form-control {{ $errors->has('point') ? ' is-invalid' : '' }}" name="point" id="point"
                                   required value={{$item->point}}>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="money" class="col-md-4 col-form-label text-md-right">银两</label>
                        <div class="col-md-6">
                            <input type="number" class="border-0 w-100 form-control {{ $errors->has('money') ? ' is-invalid' : '' }}" name="money" id="money"
                                   required value={{$item->money}}>
                        </div>
                    </div>

                    <button type="submit" class="btn btn-info btn-block">上传</button>
                </form>
            </div>
        </div>

    </div>

@endsection

resources/views/item/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @include('item.item_tab')
        </div>
        <hr>
        @include('layouts.feedback')
        <table class="table table-bordered table-hover text-center">
            <thead>
            <tr>
                <td>
                    <h1>ID</h1>
                </td>
                <td>
                    <h1>名称</h1>
                </td>
                <td>
                    <h1>描述</h1>
                </td>
                <td>
                    <h1>积分</h1>
                </td>
                <td>
                    <h1>银两</h1>
                </td>
                <td>
                    <h1>图片</h1>
                </td>
                <td>
                    <h1>操作</h1>
                </td>
            </tr>
            </thead>
            @foreach($items as $item)
                <tr>
                    <td><h2>{{$item['id']}}</h2></td>
                    <td><p>{{$item['name']}}</p></td>
                    <td><p>{{$item['description']}}</p></td>
                    <td><p>{{$item['point']}}</p></td>
                    <td><p>{{$item['money']}}</p></td>
                    <td>
                        <img src="storage/{{$item['image_url']}}" style="width:100px;height:100px">
                    </td>

                    <td>
                        <div class="btn-group-vertical d-flex">
                            <a href="{{action('ItemController@edit', $item['id'])}}" class="btn btn-info">编辑</a>
                            <form action="{{action('ItemController@destroy',$item['id'])}}" class="w-100" method="post">
                                @csrf
                                <input name="_method" type="hidden" value="DELETE">
                                <button onclick="return confirm('确定删除吗？')" type="submit" class="btn btn-danger">删除</button>
                            </form>
                        </div>
                    </td>
                </tr>

            @endforeach

        </table>
    </div>

@endsection

resources/views/item/item_tab.blade.php
<div class="container-fluid">
    <div class="col-md-6 offset-3 btn-group d-flex" role="group">
        <a href="{{ route('items.index') }}" class="btn btn-info w-100">全部商品</a>
        <a href="{{ route('items.create') }}" class="btn btn-info w-100">添加商品</a>
    </div>
</div>