routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::get('/home', function () {
    return view('welcome');
});

Auth::routes();

//Route::get('/categories/order','CategoryController@order')->middleware('admin')->name('categories.order');

Route::resource('categories', 'CategoryController')->middleware('admin');


Route::resource('collections', 'CollectionController')->middleware('admin');
Route::resource('hobbies', 'HobbyController')->middleware('admin');
Route::post('hobbies/create/get_cate_id_by_collection_id','CategoryController@get_cate_by_collection_id');

Route::resource('activities', 'ActivityController')->middleware('admin');
Route::resource('items', 'ItemController')->middleware('admin');

app/Hobby.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Hobby extends Model
{
    protected $fillable = [
        'content','user_id','image_url','collection_id','cate_id'
    ];


    public function comments()
    {
        return $this->hasMany('App\Comment');
    }

    public function likes(){
        return $this->hasMany('App\Like');
    }

    public function users()
    {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/HobbyController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Hobby;
use App\Collection;
use Illuminate\Http\Request;
use Auth;
use Illuminate\Support\Facades\Storage;

class HobbyController extends Controller
{
    public function post(Request $request){
        $user=Auth::user();
        $hobby=new Hobby();
        $hobby->content=$request->input('content');
        $hobby->user_id=$user->id;
        $hobby->cate_id=$request->cate_id;
        $hobby->collection_id=$request->collection_id;
        $hobby->save();

        if ($request->has('image_url') && $files = $request->get('image_url')) {
            $i=0;
            $images = array();
            foreach ($files as $file_string){
                $file_string=str_replace('data:image/png;base64,', '', $file_string);
                $file_string = str_replace(' ', '+', $file_string);
                $imageName = $hobby->id.'_'.$i.'.png';
                Storage::put( "hobbies_image/". $imageName, base64_decode($file_string));
                $images[] = storage_path(). '/hobbies_image/' . $imageName;
                $i++;
            }
            $hobby->image_url = implode("|", $images);
            $hobby->save();
        }

        return response()->json(['message' => 'success'],200);
    }

    public function all(){
        $hobbies=Hobby::all();
        foreach($hobbies as $hobby){
            $hobby['comments']=$hobby->comments;
        }
        return response()->json($hobbies,200);
    }

    public function get_by_cate_id($id){
        $hobbies=Hobby::where("cate_id",$id)->get();
        foreach($hobbies as $hobby){
            $hobby['comments']=$hobby->comments;
        }
        return response()->json($hobbies,200);
    }


    public function index()
    {
        $hobbies=Hobby::all();
        return view('hobbies.index',compact('hobbies'));
    }


    public function create()
    {
        $collections = Collection::all();
        return view('hobbies.create',compact('collections'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $hobby=new Hobby();
        $user=Auth::user();
        $hobby->content=$request->get('content');
        if ($request->has('image_url') && $files = $request->file('image_url')) {
            $images = array();

            foreach ($files as $file) {
                if ($file->isValid()) {
                    $img_path = $file->store('hobbies_image');
                    $images[] = $img_path;
                } else {
                    return redirect(route('hobbies'))->with('fail', '上传失败');
                }
            }
            $hobby->image_url = implode("|", $images);
            $hobby->user_id=$user->id;
            $hobby->cate_id=$request->cate_id;
            $hobby->collection_id=$request->collection_id;
            $hobby->save();
            return redirect(action('HobbyController@index'))->with('success','上传成功');
        }

       /* $collection = new Collection();
        $collection->name = $request->get('name');
        $collection->save();
        return redirect('collections')->with('success','已添加类别');*/
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // $category = Category::find($id);
        //  $products = $category->products->sortBy('name');
        //  return view('categories.show',compact('category','products','id'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $hobby=Hobby::find($id);
        $collections=Collection::all();
        $categories=Category::all();
        return view('hobbies.edit',compact('hobby','collections','categories','id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $hobby=Hobby::find($id);
        $user=Auth::user();
        if ($request->has('image_url') && $files = $request->file('image_url')) {

            if(count($files)>0){
                $images = array();
                foreach ($files as $file) {
                    if ($file->isValid()) {
                        $img_path = $file->store('hobbies_image');
                        $images[] = $img_path;
                    } else {
                        return redirect(route('hobbies'))->with('fail', '上传失败');
                    }
                }
                $hobby->image_url = implode("|", $images);
            }


        }
        $hobby->content=$request->get('content');
        $hobby->user_id=$user->id;
        $hobby->cate_id=$request->cate_id;
        $hobby->collection_id=$request->collection_id;;
        $hobby->save();
        return redirect(action('HobbyController@index'))->with('success','更新成功');


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $hobby = Hobby::find($id);
        $hobby->comments()->delete();
        $hobby->likes()->delete();
        $hobby->delete();
        return redirect('hobbies')->with('success', '删除成功');

    }

}

resources/views/hobbies/create.blade.php
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <meta name="csrf-token" content="{{ csrf_token() }}">
</head>
@extends('layouts.app')

@section('content')

    @include('layouts.feedback')
    @include('hobbies.hobby_tab')
    <div class="container-fluid mt-2 mb-5">

        <div class="card">

                <div class="card-footer">
                    <form method="post" action="{{ action('HobbyController@store') }}" enctype="multipart/form-data">
                    @csrf

                            <div class="mb-3">
                                <div class="mb-2">
                                    <span class="text-left"><b>图片上传（可上传多张）</b></span>
                                </div>
                                <div class="bg-white row pl-3 pr-3 pt-2 pb-2">
                                    <div class="w-100">
                                        <input type="file" class="form-control {{ $errors->has('image_url') ? ' is-invalid' : '' }} border-0 w-100" name="image_url[]" id="image_url" multiple
                                               required>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="collection_id" class="col-md-4 col-form-label text-md-right">上层类别</label>
                                <div class="col-md-6">
                                    <select class="form-control {{ $errors->has('collection_id') ? ' is-invalid' : '' }}"
                                            name="collection_id" id="collection_id" required>
                                        <option>类别</option>
                                        @foreach($collections as $collection)
                                            <option value="{{$collection->id}}">{{$collection->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="cate_id" class="col-md-4 col-form-label text-md-right">上层类别</label>
                                <div class="col-md-6">
                                    <select class="form-control {{ $errors->has('cate_id') ? ' is-invalid' : '' }}"
                                            name="cate_id" id="cate_id" required>
                                        <option>请选择类别</option>
                                    </select>
                                </div>
                            </div>

                            <textarea  type="text" class="form-control {{ $errors->has('content') ? ' is-invalid' : '' }} mb-2" name="content" id="content"
                                       placeholder="填写内容" required>

                            </textarea>

                            <button type="submit" class="btn btn-info btn-block">上传</button>
                    </form>
                </div>
            </div>

    </div>

@endsection

resources/views/hobbies/edit.blade.php
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <meta name="csrf-token" content="{{ csrf_token() }}">
</head>
@extends('layouts.app')

@section('content')

    @include('layouts.feedback')
    @include('hobbies.hobby_tab')
    <script src="{{asset('/js/get_cate.js')}}"></script>
    <div class="container-fluid mt-2 mb-5">
        <div class="card">

            <div class="card-footer">
                <form method="post" action="{{ route('hobbies.update', $id) }}" enctype="multipart/form-data">

                    @csrf
                    @include('layouts.feedback')
                    <input name="_method" type="hidden" value="PATCH">
                    <div class="mb-3">
                        <div class="mb-2">
                            <span class="text-left"><b>图片上传（可上传多张）</b></span>
                        </div>
                        <div class="bg-white row pl-3 pr-3 pt-2 pb-2">
                            <div class="w-100">
                                <input type="file" class="border-0 form-control {{ $errors->has('image_url') ? ' is-invalid' : '' }} w-100" name="image_url[]" id="image_url" multiple
                                       >
                            </div>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="collection_id" class="col-md-4 col-form-label text-md-right">上层类别</label>
                        <div class="col-md-6">
                            <select class="form-control {{ $errors->has('collection_id') ? ' is-invalid' : '' }}"
                                    name="collection_id" id="collection_id" required>
                                <option>类别</option>
                                @foreach($collections as $collection)
                                    <option value="{{$collection->id}}" @if($collection->id == $hobby->collection_id) selected @endif >{{$collection->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="cate_id" class="col-md-4 col-form-label text-md-right">上层类别</label>
                        <div class="col-md-6">
                            <select class="form-control {{ $errors->has('cate_id') ? ' is-invalid' : '' }}"
                                    name="cate_id" id="cate_id" required>
                                @foreach($categories as $category)
                                    <option value="{{$category->id}}" @if($category->id == $hobby->collection_id) selected @endif >{{$category->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <textarea  type="text" class="form-control {{ $errors->has('content') ? ' is-invalid' : '' }} mb-2" name="content" id="content"
                               placeholder="填写内容" required>{{$hobby->content}}</textarea>

                    <button type="submit" class="btn btn-info btn-block">上传</button>
                </form>
            </div>
        </div>

    </div>

@endsection

resources/views/hobbies/hobby_tab.blade.php
<div class="container-fluid">
    <div class="col-md-6 offset-3 btn-group d-flex" role="group">
        <a href="{{ route('hobbies.index') }}" class="btn btn-info w-100">全部兴趣</a>
        <a href="{{ route('hobbies.create') }}" class="btn btn-info w-100">添加兴趣</a>
    </div>
</div>

resources/views/hobbies/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @include('hobbies.hobby_tab')
        </div>
        <hr>
        @include('layouts.feedback')
        <table class="table table-bordered table-hover text-center">
            <thead>
            <tr>
                <td>
                    <h1>ID</h1>
                </td>
                <td>
                    <h1>内容</h1>
                </td>
                <td>
                    <h1>图片</h1>
                </td>
                <td>
                    <h1>操作</h1>
                </td>
            </tr>
            </thead>
            @foreach($hobbies as $hobby)
                <tr>
                    <td><h2>{{$hobby['id']}}</h2></td>
                    <td><p>{{$hobby['content']}}</p></td>

                    <td>
                        @foreach(explode('|',$hobby['image_url']) as $img)
                            <h5>{{$hobby['img_url']}}</h5>
                            <img src="storage/{{$img}}"
                                 style="width:100px;height:100px">
                        @endforeach
                    </td>

                    <td>
                        <div class="btn-group-vertical d-flex">
                            <a href="{{action('HobbyController@edit', $hobby['id'])}}" class="btn btn-info">编辑</a>
                            <form action="{{action('HobbyController@destroy',$hobby['id'])}}" class="w-100" method="post">
                                @csrf
                                <input name="_method" type="hidden" value="DELETE">
                                <button onclick="return confirm('确定删除吗？')" type="submit" class="btn btn-danger">删除</button>
                            </form>
                        </div>
                    </td>
                </tr>

            @endforeach

        </table>
    </div>

@endsection